
DATE_FORMAT = '%d-%m-%Y'
DATETIME_FORMAT = '%e %b %Y %H:%M:%S'

TREASURY_URL = "https://home.treasury.gov/sites/default/files/interest-rates/yield.xml"
DELTA_DIFFERENTIAL = 1.e-3
VEGA_DIFFERENTIAL = 1.e-4
GAMMA_DIFFERENTIAL = 1.e-3
RHO_DIFFERENTIAL = 1.e-4
THETA_DIFFERENTIAL = 1.e-5

IMPLIED_VOLATILITY_TOLERANCE = 1.e-6
SOLVER_STARTING_VALUE = 0.27

OVERNIGHT_RATE = 0
FALLBACK_RISK_FREE_RATE = 0.02
